In [1]:
import numpy as np

In [2]:
#creating array 
b = np.array([2,4,5,7,2,5])
b

array([2, 4, 5, 7, 2, 5])

In [4]:
b = np.ones(3)
b

array([1., 1., 1.])

In [5]:
b = np.zeros((2,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
b = np.full((3,3),9)
b

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [8]:
b = np.empty(3)
b

array([1., 1., 1.])

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b = np.zeros(10, dtype=int)
b[4] = 1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [15]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [20]:
b = np.linspace(1,10)
b
print(b[1]-b[0])
print(b[2]-b[1])

0.18367346938775508
0.18367346938775508


In [21]:
b = np.linspace(1,10,4)
b

array([ 1.,  4.,  7., 10.])

In [23]:
b = np.random.rand(10)
b

array([0.44103474, 0.81172064, 0.41855299, 0.86087775, 0.58356954,
       0.27652131, 0.23712033, 0.78045609, 0.41748399, 0.60500267])

In [24]:
b = np.random.rand(10) * 10
b

array([6.77200734, 7.7952456 , 9.61527841, 9.18067986, 1.19910149,
       6.45520324, 7.1679588 , 4.67270192, 0.70083301, 6.59719444])

In [51]:
b = np.random.randint(10)
b

9

In [52]:
b = np.random.randint(10,20)
b

18

In [53]:
b = np.random.randint(10,20,3)
b

array([12, 10, 16])

In [55]:
b = np.arange(9,50)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [56]:
b = np.eye(5,6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [59]:
#You are given a rope of length 5cm. Cut the rope into 9 parts
#such that each part is equal length
b = np.linspace(0, 5,9, dtype=float)
b

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [73]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
print(arr[2,:3])

[11 12 13]


In [77]:
print(arr[1:,3])

[ 9 14 19]


In [78]:
print(arr[2:,:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [79]:
print(arr[1:3,1:3])

[[ 7  8]
 [12 13]]


In [87]:
b = np.array([1,2,0,0,4,0])
b

array([1, 2, 0, 0, 4, 0])

In [83]:
non_zero = b[b !=0]
print(non_zero)


[1 2 4]


In [90]:
indx = np.where(b==0)
print(indx)

(array([2, 3, 5], dtype=int64),)


In [91]:
indx = np.where(b!=0)
print(indx)

(array([0, 1, 4], dtype=int64),)


In [97]:
arr = np.arange(1, 20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [101]:
indx = np.where(arr % 3==0)
indx

(array([1, 4, 7], dtype=int64),)

In [121]:

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr[arr % 2==1]  = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [168]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [175]:
indx = np.where((arr < 3) | (arr >8))
arr[indx]

array([ 1,  2,  9, 10])

In [185]:
age = np.random.randint(18,24,20)
height = np.random.randint(140, 160, 20)
print(age)
print(height)

[19 19 22 19 21 19 19 19 18 20 22 22 20 21 18 20 18 18 23 18]
[141 141 152 144 154 140 153 153 156 154 142 158 150 151 140 148 154 158
 148 157]


In [186]:
students = age[height> 150]
students

array([22, 21, 19, 19, 18, 20, 22, 21, 18, 18, 18])